/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedTechnicianRouteImport } from './routes/_authenticated/technician'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedImportExportRouteImport } from './routes/_authenticated/import-export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedWorkOrdersIndexRouteImport } from './routes/_authenticated/work-orders.index'
import { Route as AuthenticatedWorkOrdersNewRouteImport } from './routes/_authenticated/work-orders.new'
import { Route as AuthenticatedWorkOrdersIdRouteImport } from './routes/_authenticated/work-orders.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechnicianRoute = AuthenticatedTechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportExportRoute =
  AuthenticatedImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkOrdersIndexRoute =
  AuthenticatedWorkOrdersIndexRouteImport.update({
    id: '/work-orders/',
    path: '/work-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkOrdersNewRoute =
  AuthenticatedWorkOrdersNewRouteImport.update({
    id: '/work-orders/new',
    path: '/work-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkOrdersIdRoute =
  AuthenticatedWorkOrdersIdRouteImport.update({
    id: '/work-orders/$id',
    path: '/work-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/technician': typeof AuthenticatedTechnicianRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/work-orders/$id': typeof AuthenticatedWorkOrdersIdRoute
  '/work-orders/new': typeof AuthenticatedWorkOrdersNewRoute
  '/work-orders/': typeof AuthenticatedWorkOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/technician': typeof AuthenticatedTechnicianRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/work-orders/$id': typeof AuthenticatedWorkOrdersIdRoute
  '/work-orders/new': typeof AuthenticatedWorkOrdersNewRoute
  '/work-orders': typeof AuthenticatedWorkOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import-export': typeof AuthenticatedImportExportRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/technician': typeof AuthenticatedTechnicianRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/work-orders/$id': typeof AuthenticatedWorkOrdersIdRoute
  '/_authenticated/work-orders/new': typeof AuthenticatedWorkOrdersNewRoute
  '/_authenticated/work-orders/': typeof AuthenticatedWorkOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/activity'
    | '/dashboard'
    | '/import-export'
    | '/properties'
    | '/reports'
    | '/schedule'
    | '/technician'
    | '/tenants'
    | '/units'
    | '/users'
    | '/work-orders/$id'
    | '/work-orders/new'
    | '/work-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/activity'
    | '/dashboard'
    | '/import-export'
    | '/properties'
    | '/reports'
    | '/schedule'
    | '/technician'
    | '/tenants'
    | '/units'
    | '/users'
    | '/work-orders/$id'
    | '/work-orders/new'
    | '/work-orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/dashboard'
    | '/_authenticated/import-export'
    | '/_authenticated/properties'
    | '/_authenticated/reports'
    | '/_authenticated/schedule'
    | '/_authenticated/technician'
    | '/_authenticated/tenants'
    | '/_authenticated/units'
    | '/_authenticated/users'
    | '/_authenticated/work-orders/$id'
    | '/_authenticated/work-orders/new'
    | '/_authenticated/work-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technician': {
      id: '/_authenticated/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof AuthenticatedTechnicianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-export': {
      id: '/_authenticated/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AuthenticatedImportExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-orders/': {
      id: '/_authenticated/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof AuthenticatedWorkOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-orders/new': {
      id: '/_authenticated/work-orders/new'
      path: '/work-orders/new'
      fullPath: '/work-orders/new'
      preLoaderRoute: typeof AuthenticatedWorkOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-orders/$id': {
      id: '/_authenticated/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/work-orders/$id'
      preLoaderRoute: typeof AuthenticatedWorkOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportExportRoute: typeof AuthenticatedImportExportRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedTechnicianRoute: typeof AuthenticatedTechnicianRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWorkOrdersIdRoute: typeof AuthenticatedWorkOrdersIdRoute
  AuthenticatedWorkOrdersNewRoute: typeof AuthenticatedWorkOrdersNewRoute
  AuthenticatedWorkOrdersIndexRoute: typeof AuthenticatedWorkOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportExportRoute: AuthenticatedImportExportRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedTechnicianRoute: AuthenticatedTechnicianRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWorkOrdersIdRoute: AuthenticatedWorkOrdersIdRoute,
  AuthenticatedWorkOrdersNewRoute: AuthenticatedWorkOrdersNewRoute,
  AuthenticatedWorkOrdersIndexRoute: AuthenticatedWorkOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
