/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTechnicianRouteImport } from './routes/_authenticated/technician'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedImportExportRouteImport } from './routes/_authenticated/import-export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin-settings'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedWorkOrdersIndexRouteImport } from './routes/_authenticated/work-orders.index'
import { Route as AuthenticatedUnitsIndexRouteImport } from './routes/_authenticated/units.index'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants.index'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedWorkOrdersNewRouteImport } from './routes/_authenticated/work-orders.new'
import { Route as AuthenticatedWorkOrdersIdRouteImport } from './routes/_authenticated/work-orders.$id'
import { Route as AuthenticatedUnitsIdRouteImport } from './routes/_authenticated/units.$id'
import { Route as AuthenticatedTenantsIdRouteImport } from './routes/_authenticated/tenants.$id'
import { Route as AuthenticatedPropertiesIdRouteImport } from './routes/_authenticated/properties.$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTechnicianRoute = AuthenticatedTechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportExportRoute =
  AuthenticatedImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin-settings',
    path: '/admin-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkOrdersIndexRoute =
  AuthenticatedWorkOrdersIndexRouteImport.update({
    id: '/work-orders/',
    path: '/work-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUnitsIndexRoute = AuthenticatedUnitsIndexRouteImport.update({
  id: '/units/',
  path: '/units/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkOrdersNewRoute =
  AuthenticatedWorkOrdersNewRouteImport.update({
    id: '/work-orders/new',
    path: '/work-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkOrdersIdRoute =
  AuthenticatedWorkOrdersIdRouteImport.update({
    id: '/work-orders/$id',
    path: '/work-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUnitsIdRoute = AuthenticatedUnitsIdRouteImport.update({
  id: '/units/$id',
  path: '/units/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsIdRoute = AuthenticatedTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesIdRoute =
  AuthenticatedPropertiesIdRouteImport.update({
    id: '/properties/$id',
    path: '/properties/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/technician': typeof AuthenticatedTechnicianRoute
  '/users': typeof AuthenticatedUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/units/$id': typeof AuthenticatedUnitsIdRoute
  '/work-orders/$id': typeof AuthenticatedWorkOrdersIdRoute
  '/work-orders/new': typeof AuthenticatedWorkOrdersNewRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/units/': typeof AuthenticatedUnitsIndexRoute
  '/work-orders/': typeof AuthenticatedWorkOrdersIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/import-export': typeof AuthenticatedImportExportRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/technician': typeof AuthenticatedTechnicianRoute
  '/users': typeof AuthenticatedUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/units/$id': typeof AuthenticatedUnitsIdRoute
  '/work-orders/$id': typeof AuthenticatedWorkOrdersIdRoute
  '/work-orders/new': typeof AuthenticatedWorkOrdersNewRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
  '/units': typeof AuthenticatedUnitsIndexRoute
  '/work-orders': typeof AuthenticatedWorkOrdersIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin-settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/import-export': typeof AuthenticatedImportExportRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/technician': typeof AuthenticatedTechnicianRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/properties/$id': typeof AuthenticatedPropertiesIdRoute
  '/_authenticated/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/_authenticated/units/$id': typeof AuthenticatedUnitsIdRoute
  '/_authenticated/work-orders/$id': typeof AuthenticatedWorkOrdersIdRoute
  '/_authenticated/work-orders/new': typeof AuthenticatedWorkOrdersNewRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/_authenticated/units/': typeof AuthenticatedUnitsIndexRoute
  '/_authenticated/work-orders/': typeof AuthenticatedWorkOrdersIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/reset-password'
    | '/unsubscribe'
    | '/activity'
    | '/admin-settings'
    | '/dashboard'
    | '/import-export'
    | '/reports'
    | '/schedule'
    | '/technician'
    | '/users'
    | '/email/unsubscribe'
    | '/properties/$id'
    | '/tenants/$id'
    | '/units/$id'
    | '/work-orders/$id'
    | '/work-orders/new'
    | '/lovable/email/suppression'
    | '/properties/'
    | '/tenants/'
    | '/units/'
    | '/work-orders/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/auth'
    | '/reset-password'
    | '/unsubscribe'
    | '/activity'
    | '/admin-settings'
    | '/dashboard'
    | '/import-export'
    | '/reports'
    | '/schedule'
    | '/technician'
    | '/users'
    | '/email/unsubscribe'
    | '/properties/$id'
    | '/tenants/$id'
    | '/units/$id'
    | '/work-orders/$id'
    | '/work-orders/new'
    | '/lovable/email/suppression'
    | '/properties'
    | '/tenants'
    | '/units'
    | '/work-orders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/auth'
    | '/reset-password'
    | '/unsubscribe'
    | '/_authenticated/activity'
    | '/_authenticated/admin-settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/import-export'
    | '/_authenticated/reports'
    | '/_authenticated/schedule'
    | '/_authenticated/technician'
    | '/_authenticated/users'
    | '/email/unsubscribe'
    | '/_authenticated/properties/$id'
    | '/_authenticated/tenants/$id'
    | '/_authenticated/units/$id'
    | '/_authenticated/work-orders/$id'
    | '/_authenticated/work-orders/new'
    | '/lovable/email/suppression'
    | '/_authenticated/properties/'
    | '/_authenticated/tenants/'
    | '/_authenticated/units/'
    | '/_authenticated/work-orders/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technician': {
      id: '/_authenticated/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof AuthenticatedTechnicianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-export': {
      id: '/_authenticated/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AuthenticatedImportExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-settings': {
      id: '/_authenticated/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-orders/': {
      id: '/_authenticated/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof AuthenticatedWorkOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units/': {
      id: '/_authenticated/units/'
      path: '/units'
      fullPath: '/units/'
      preLoaderRoute: typeof AuthenticatedUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work-orders/new': {
      id: '/_authenticated/work-orders/new'
      path: '/work-orders/new'
      fullPath: '/work-orders/new'
      preLoaderRoute: typeof AuthenticatedWorkOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-orders/$id': {
      id: '/_authenticated/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/work-orders/$id'
      preLoaderRoute: typeof AuthenticatedWorkOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units/$id': {
      id: '/_authenticated/units/$id'
      path: '/units/$id'
      fullPath: '/units/$id'
      preLoaderRoute: typeof AuthenticatedUnitsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/$id': {
      id: '/_authenticated/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof AuthenticatedTenantsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$id': {
      id: '/_authenticated/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AuthenticatedPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImportExportRoute: typeof AuthenticatedImportExportRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedTechnicianRoute: typeof AuthenticatedTechnicianRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedPropertiesIdRoute: typeof AuthenticatedPropertiesIdRoute
  AuthenticatedTenantsIdRoute: typeof AuthenticatedTenantsIdRoute
  AuthenticatedUnitsIdRoute: typeof AuthenticatedUnitsIdRoute
  AuthenticatedWorkOrdersIdRoute: typeof AuthenticatedWorkOrdersIdRoute
  AuthenticatedWorkOrdersNewRoute: typeof AuthenticatedWorkOrdersNewRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
  AuthenticatedUnitsIndexRoute: typeof AuthenticatedUnitsIndexRoute
  AuthenticatedWorkOrdersIndexRoute: typeof AuthenticatedWorkOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImportExportRoute: AuthenticatedImportExportRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedTechnicianRoute: AuthenticatedTechnicianRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedPropertiesIdRoute: AuthenticatedPropertiesIdRoute,
  AuthenticatedTenantsIdRoute: AuthenticatedTenantsIdRoute,
  AuthenticatedUnitsIdRoute: AuthenticatedUnitsIdRoute,
  AuthenticatedWorkOrdersIdRoute: AuthenticatedWorkOrdersIdRoute,
  AuthenticatedWorkOrdersNewRoute: AuthenticatedWorkOrdersNewRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
  AuthenticatedUnitsIndexRoute: AuthenticatedUnitsIndexRoute,
  AuthenticatedWorkOrdersIndexRoute: AuthenticatedWorkOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
